### ISSUE TITLE
fbexpect requires hhvm ^3.28 or ^4.0, but all code is in dothack files.

### ISSUE THREAD

**Issue by lexidor** [hhvm/fbexpect#9]
Composer does not warn you that the newest versions of fbexpect will not run on hhvm 3.30.4. Meaning that the installed version will have dothack files, which hhvm 3.30.4 does not understand.

**Comment by fredemmott** [comment]
retagged v2.4.0 as v2.5.4, and released a new v2.5.5 for 4.0 users - thanks!
